dataset_params:
  im_path: 'data/cifar10_data'
  im_test_path: 'data/cifar10_data'
  canny_im_size: 32
  download: False

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  
model_params:
  im_channels: 3
  in_channels: 3
  im_size: 32
  hint_channels: 3
  down_channels: [64, 128, 256, 512]
  mid_channels: [512, 512, 256]
  down_sample: [True, True, False]
  time_emb_dim: 128
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  num_heads: 4
  
train_params:
  task_name: 'cifar10'
  batch_size: 32
  num_epochs: 200
  controlnet_epochs: 200
  num_samples: 25
  num_grid_rows: 5
  ddpm_lr: 0.0001
  controlnet_lr: 0.0001
  ddpm_ckpt_name: 'ddpm_cifar10_ckpt.pth'
  controlnet_ckpt_name: 'ddpm_controlnet_cifar10_ckpt.pth'
  consistency_epochs: 30
  consistency_lr: 0.0001
  distribution_matching_epochs: 30
  distribution_matching_lr: 0.00005